// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface BreadcrumbItem {
  label?: string;
  href?: string;
  is_current?: boolean;
  component: "breadcrumb_item";
  _uid: string;
}
