// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { EcommerceServicePage } from './EcommerceServicePage.d.ts';
import type { LandingPage } from './LandingPage.d.ts';
import type { Page } from './Page.d.ts';
export type ContentType =
  | EcommerceServicePage
  | LandingPage
  | Page;