// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { LandingPage } from './LandingPage.d.ts';
import type { Page } from './Page.d.ts';
import type { Test2 } from './Test2.d.ts';
export type ContentType =
  | LandingPage
  | Page
  | Test2;