// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
import type { NavItem } from './NavItem.d.ts';
export interface Header {
  Logo?: StoryblokAsset;
  items?: NavItem[];
  component: "Header";
  _uid: string;
}
