// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface HeroStatItem {
  value?: string;
  label?: string;
  component: "hero_stat_item";
  _uid: string;
}
