// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface HeroCollageImage {
  image?: StoryblokAsset;
  alt?: string;
  mobile_image?: StoryblokAsset;
  component: "hero_collage_image";
  _uid: string;
}
