// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
import type { BreadcrumbItem } from './BreadcrumbItem.d.ts';
import type { BusinessSolutionsSection } from './BusinessSolutionsSection.d.ts';
import type { CaseStudiesSection } from './CaseStudiesSection.d.ts';
import type { ExpertiseSection } from './ExpertiseSection.d.ts';
import type { HeroSection } from './HeroSection.d.ts';
export interface LandingPage {
  title?: string;
  description?: string;
  seo_title?: string;
  seo_description?: string;
  og_image?: StoryblokAsset;
  breadcrumbs?: BreadcrumbItem[];
  body?: (HeroSection | BusinessSolutionsSection | CaseStudiesSection | ExpertiseSection)[];
  component: "landing_page";
  _uid: string;
}
