// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
import type { HeroCollageImage } from './HeroCollageImage.d.ts';
import type { HeroStatItem } from './HeroStatItem.d.ts';
export interface SectionHeroStellar {
  badge_text?: string;
  title?: string;
  description?: string;
  primary_cta_label?: string;
  primary_cta_link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  primary_cta_avatar?: StoryblokAsset;
  primary_cta_online_indicator?: boolean;
  helper_text?: string;
  stats?: HeroStatItem[];
  collage_images?: HeroCollageImage[];
  hidden?: boolean;
  component: "section_hero_stellar";
  _uid: string;
}
