// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
import type { BreadcrumbItem } from './BreadcrumbItem.d.ts';
import type { BusinessSolutionsSection } from './BusinessSolutionsSection.d.ts';
import type { CaseStudiesSection } from './CaseStudiesSection.d.ts';
import type { ExpertiseSection } from './ExpertiseSection.d.ts';
import type { Header } from './Header.d.ts';
import type { HeroSection } from './HeroSection.d.ts';
import type { IndustriesSection } from './IndustriesSection.d.ts';
import type { LaunchPlatformSection } from './LaunchPlatformSection.d.ts';
import type { PlatformsExpertiseSection } from './PlatformsExpertiseSection.d.ts';
import type { ServicesSection } from './ServicesSection.d.ts';
import type { SiteFooter } from './SiteFooter.d.ts';
import type { WhyUsSection } from './WhyUsSection.d.ts';
export interface Test2 {
  title?: string;
  description?: string;
  seo_title?: string;
  seo_description?: string;
  og_image?: StoryblokAsset;
  breadcrumbs?: BreadcrumbItem[];
  header?: Header[];
  sections?: (
    | HeroSection
    | WhyUsSection
    | ExpertiseSection
    | CaseStudiesSection
    | BusinessSolutionsSection
    | ServicesSection
    | PlatformsExpertiseSection
    | LaunchPlatformSection
    | IndustriesSection
  )[];
  footer?: SiteFooter[];
  component: "test-2";
  _uid: string;
}
